# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast implementation of pracma::trapz from the Armadillo C++ library
#'
#' Compute the area of a multivariate function with (matrix) values Y at the points x.
#'
#' @param x x-coordinates of points on the x-axis (vector)
#' @param y y-coordinates of function values (matrix)
#' @param dim an integer giving the subscripts which the function will be applied over. 1 indicates rows, 2 indicates columns
#' @export
fastTrapz <- function(X, Y, dim) {
    .Call(`_resourcecode_fastTrapz`, X, Y, dim)
}

